-- MySQL Script generated by MySQL Workbench
-- Qua 16 Out 2019 10:10:38 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefones` (
  `Telefone` INT(9) NOT NULL,
  `Cliente_CPF` INT NULL,
  `Funcionario_CPF` INT NULL,
  PRIMARY KEY (`Telefone`),
  INDEX `fk_Telefones_Cliente_idx` (`Cliente_CPF` ASC),
  INDEX `fk_Telefones_Funcionario1_idx` (`Funcionario_CPF` ASC),
  CONSTRAINT `fk_Telefones_Cliente`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefones_Funcionario1`
    FOREIGN KEY (`Funcionario_CPF`)
    REFERENCES `mydb`.`Funcionario` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brinquedos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brinquedos` (
  `Cod_brinquedo` INT NOT NULL,
  `Preco` INT(10) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_brinquedo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario_has_Brinquedos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario_has_Brinquedos` (
  `Funcionario_CPF` INT NOT NULL,
  `Brinquedos_Cod_brinquedo` INT NOT NULL,
  PRIMARY KEY (`Funcionario_CPF`, `Brinquedos_Cod_brinquedo`),
  INDEX `fk_Funcionario_has_Brinquedos_Brinquedos1_idx` (`Brinquedos_Cod_brinquedo` ASC),
  INDEX `fk_Funcionario_has_Brinquedos_Funcionario1_idx` (`Funcionario_CPF` ASC),
  CONSTRAINT `fk_Funcionario_has_Brinquedos_Funcionario1`
    FOREIGN KEY (`Funcionario_CPF`)
    REFERENCES `mydb`.`Funcionario` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_has_Brinquedos_Brinquedos1`
    FOREIGN KEY (`Brinquedos_Cod_brinquedo`)
    REFERENCES `mydb`.`Brinquedos` (`Cod_brinquedo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartao_cobranca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartao_cobranca` (
  `Data` DATE NOT NULL,
  `Hora` VARCHAR(45) NOT NULL,
  `Telefones_Telefone` INT(9) NOT NULL,
  PRIMARY KEY (`Data`, `Hora`, `Telefones_Telefone`),
  INDEX `fk_Cartao_cobranca_Telefones1_idx` (`Telefones_Telefone` ASC),
  CONSTRAINT `fk_Cartao_cobranca_Telefones1`
    FOREIGN KEY (`Telefones_Telefone`)
    REFERENCES `mydb`.`Telefones` (`Telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brinquedos_has_Cartao_cobranca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brinquedos_has_Cartao_cobranca` (
  `Brinquedos_Cod_brinquedo` INT NOT NULL,
  `Cartao_cobranca_Data` DATE NOT NULL,
  `Cartao_cobranca_Hora` VARCHAR(45) NOT NULL,
  `Cartao_cobranca_Telefones_Telefone` INT(9) NOT NULL,
  PRIMARY KEY (`Brinquedos_Cod_brinquedo`, `Cartao_cobranca_Data`, `Cartao_cobranca_Hora`, `Cartao_cobranca_Telefones_Telefone`),
  INDEX `fk_Brinquedos_has_Cartao_cobranca_Cartao_cobranca1_idx` (`Cartao_cobranca_Data` ASC, `Cartao_cobranca_Hora` ASC, `Cartao_cobranca_Telefones_Telefone` ASC),
  INDEX `fk_Brinquedos_has_Cartao_cobranca_Brinquedos1_idx` (`Brinquedos_Cod_brinquedo` ASC),
  CONSTRAINT `fk_Brinquedos_has_Cartao_cobranca_Brinquedos1`
    FOREIGN KEY (`Brinquedos_Cod_brinquedo`)
    REFERENCES `mydb`.`Brinquedos` (`Cod_brinquedo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Brinquedos_has_Cartao_cobranca_Cartao_cobranca1`
    FOREIGN KEY (`Cartao_cobranca_Data` , `Cartao_cobranca_Hora` , `Cartao_cobranca_Telefones_Telefone`)
    REFERENCES `mydb`.`Cartao_cobranca` (`Data` , `Hora` , `Telefones_Telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
