-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 20:15:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefones` (
  `Telefone` INT(9) NOT NULL,
  `Cliente_CPF` INT NULL,
  `Funcionario_CPF` INT NULL,
  PRIMARY KEY (`Telefone`),
  INDEX `fk_Telefones_Cliente_idx` (`Cliente_CPF` ASC) VISIBLE,
  INDEX `fk_Telefones_Funcionario1_idx` (`Funcionario_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Telefones_Cliente`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefones_Funcionario1`
    FOREIGN KEY (`Funcionario_CPF`)
    REFERENCES `mydb`.`Funcionario` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brinquedos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brinquedos` (
  `Cod_brinquedo` INT NOT NULL,
  `Preco` INT(10) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_brinquedo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario_has_Brinquedos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario_has_Brinquedos` (
  `Funcionario_CPF` INT NOT NULL,
  `Brinquedos_Cod_brinquedo` INT NOT NULL,
  PRIMARY KEY (`Funcionario_CPF`, `Brinquedos_Cod_brinquedo`),
  INDEX `fk_Funcionario_has_Brinquedos_Brinquedos1_idx` (`Brinquedos_Cod_brinquedo` ASC) VISIBLE,
  INDEX `fk_Funcionario_has_Brinquedos_Funcionario1_idx` (`Funcionario_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_has_Brinquedos_Funcionario1`
    FOREIGN KEY (`Funcionario_CPF`)
    REFERENCES `mydb`.`Funcionario` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_has_Brinquedos_Brinquedos1`
    FOREIGN KEY (`Brinquedos_Cod_brinquedo`)
    REFERENCES `mydb`.`Brinquedos` (`Cod_brinquedo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartao_cobranca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartao_cobranca` (
  `Data` DATE NOT NULL,
  `Cliente_CPF` INT NOT NULL,
  PRIMARY KEY (`Data`, `Cliente_CPF`),
  INDEX `fk_Cartao_cobranca_Cliente1_idx` (`Cliente_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Cartao_cobranca_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartao_cobranca_has_Brinquedos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartao_cobranca_has_Brinquedos` (
  `Cartao_cobranca_Data` DATE NOT NULL,
  `Cartao_cobranca_Cliente_CPF` INT NOT NULL,
  `Brinquedos_Cod_brinquedo` INT NOT NULL,
  `Hora` TIME NOT NULL,
  PRIMARY KEY (`Cartao_cobranca_Data`, `Cartao_cobranca_Cliente_CPF`, `Brinquedos_Cod_brinquedo`, `Hora`),
  INDEX `fk_Cartao_cobranca_has_Brinquedos_Brinquedos1_idx` (`Brinquedos_Cod_brinquedo` ASC) VISIBLE,
  INDEX `fk_Cartao_cobranca_has_Brinquedos_Cartao_cobranca1_idx` (`Cartao_cobranca_Data` ASC, `Cartao_cobranca_Cliente_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Cartao_cobranca_has_Brinquedos_Cartao_cobranca1`
    FOREIGN KEY (`Cartao_cobranca_Data` , `Cartao_cobranca_Cliente_CPF`)
    REFERENCES `mydb`.`Cartao_cobranca` (`Data` , `Cliente_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cartao_cobranca_has_Brinquedos_Brinquedos1`
    FOREIGN KEY (`Brinquedos_Cod_brinquedo`)
    REFERENCES `mydb`.`Brinquedos` (`Cod_brinquedo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
